name: 11
timestamp: 1600341320
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1600336859
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-5363: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-1385: Menu
  messages:
    system-messages-2137: 'System Messages'
  content:
    system-content-9741: 'Page Content'
  copyright:
    copyright-3563: Copyright
  spacer:
    spacer-8986: Spacer
  branding:
    branding-4559: Branding
  mobile-menu:
    mobile-menu-6044: Mobile-menu
inherit: {  }
