version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1600336859
layout:
  /header/:
    -
      - 'logo-5363 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-1385
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-2137
    -
      - system-content-9741
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3563 40'
      - 'spacer-8986 30'
      - 'branding-4559 30'
  offcanvas:
    -
      - mobile-menu-6044
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
