version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1600336859
layout:
  /header/:
    -
      - 'logo-7029 30'
      - 'spacer-8243 70'
  /main/:
    -
      - system-messages-3996
    -
      - system-content-3617
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9936 40'
      - 'spacer-3731 30'
      - 'branding-7837 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
