name: _error
timestamp: 1600336860
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1600336859
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9907: Logo
  spacer:
    spacer-1101: Spacer
    spacer-7502: Spacer
  menu:
    menu-9315: Menu
  content:
    system-content-2800: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-2616: Copyright
  branding:
    branding-9022: Branding
  mobile-menu:
    mobile-menu-3762: Mobile-menu
inherit: {  }
