version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1600336859
layout:
  /header/:
    -
      - 'logo-9907 30'
      - 'spacer-1101 70'
  /navigation/:
    -
      - menu-9315
  /main/:
    -
      - system-content-2800
  /footer/:
    -
      - position-footer
    -
      - 'copyright-2616 40'
      - 'spacer-7502 30'
      - 'branding-9022 30'
  offcanvas:
    -
      - mobile-menu-3762
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
