name: _body_only
timestamp: 1600336860
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1600336859
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-5412: 'System Messages'
  content:
    system-content-4326: 'Page Content'
inherit: {  }
